wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.13
    start_time: 1683524065
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.9.13
      5: 0.12.0
      6: 4.26.1
      8:
      - 1
      - 2
      - 5
